version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: myhiber_w6im
      POSTGRES_USER: myhiber_user
      POSTGRES_PASSWORD: gyrINK0QUEXra8L8kgM5TFOq4hGzDhOl
    ports:
      - 5432:5432
    # Uncomment the following line if you want to initialize the database with a script
    # volumes:
    #   - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9091:9091 
    environment:
      # Update to match PostgreSQL settings
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myhiber_w6im
      SPRING_DATASOURCE_USERNAME: myhiber_user
      SPRING_DATASOURCE_PASSWORD: gyrINK0QUEXra8L8kgM5TFOq4hGzDhOl
