version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_HOST: spring-db
      MYSQL_DATABASE: myhiber_w6im
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
    # volumes:
    #   - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9091:9091 
    environment:
      # note the change in the following line
      app:
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - db
  ports:
    - 9091:9091
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cttrrtbv2p9s738lhib0-a.oregon-postgres.render.com/myhiber_w6im
    SPRING_DATASOURCE_USERNAME: myhiber_user
    SPRING_DATASOURCE_PASSWORD: gyrINK0QUEXra8L8kgM5TFOq4hGzDhOl


