version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: myhiber_w6im
      POSTGRES_USER: myhiber_user
      POSTGRES_PASSWORD: gyrINK0QUEXra8L8kgM5TFOq4hGzDhOl
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9091:9091
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myhiber_w6im
      SPRING_DATASOURCE_USERNAME: myhiber_user
      SPRING_DATASOURCE_PASSWORD: gyrINK0QUEXra8L8kgM5TFOq4hGzDhOl
