version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_HOST: spring-db
      MYSQL_DATABASE: myhiber
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
    # volumes:
    #   - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9091:9091 
    environment:
      # note the change in the following line
      spring.datasource.url: jdbc:mysql://root:admin@host.docker.internal:3306/myhiber
      spring.datasource.username: root
      spring.datasource.password: admin
